/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author sazza
 */
public class AddRecordGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddRecordGUI
     */
    public AddRecordGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddCoachButton = new javax.swing.JButton();
        AddSportButton = new javax.swing.JButton();
        AddSportsScheduleButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("ADD RECORD");

        AddCoachButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AddCoachButton.setForeground(new java.awt.Color(222, 105, 33));
        AddCoachButton.setText("Coach");
        AddCoachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCoachButtonActionPerformed(evt);
            }
        });

        AddSportButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AddSportButton.setForeground(new java.awt.Color(204, 10, 124));
        AddSportButton.setText("Sport");
        AddSportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSportButtonActionPerformed(evt);
            }
        });

        AddSportsScheduleButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AddSportsScheduleButton.setForeground(new java.awt.Color(0, 153, 0));
        AddSportsScheduleButton.setText("Sports Schedule");
        AddSportsScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSportsScheduleButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BackButton.setForeground(new java.awt.Color(153, 0, 0));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddCoachButton)
                            .addComponent(AddSportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(AddSportsScheduleButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(AddCoachButton)
                .addGap(33, 33, 33)
                .addComponent(AddSportButton)
                .addGap(37, 37, 37)
                .addComponent(AddSportsScheduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCoachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCoachButtonActionPerformed
        dispose();
        AddRecordCoachGUI addRecordCoachGUI = new AddRecordCoachGUI();
        addRecordCoachGUI.setVisible(true);
    }//GEN-LAST:event_AddCoachButtonActionPerformed

    private void AddSportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSportButtonActionPerformed
        dispose();
        AddRecordSportGUI addRecordSportGUI = new AddRecordSportGUI();
        addRecordSportGUI.setVisible(true);
    }//GEN-LAST:event_AddSportButtonActionPerformed

    private void AddSportsScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSportsScheduleButtonActionPerformed
        dispose();
        AddRecordSportScheduleGUI addRecordSportScheduleGUI = new AddRecordSportScheduleGUI();
        addRecordSportScheduleGUI.setVisible(true);
    }//GEN-LAST:event_AddSportsScheduleButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        AdminMainGUI adminMainGUI = new AdminMainGUI();
        adminMainGUI.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCoachButton;
    private javax.swing.JButton AddSportButton;
    private javax.swing.JButton AddSportsScheduleButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
