/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author sazza
 */
public class AddRecordSportScheduleGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddRecordSportScheduleGUI
     */
    public AddRecordSportScheduleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SwimmingButton = new javax.swing.JButton();
        BadmintonButton = new javax.swing.JButton();
        FootballButton = new javax.swing.JButton();
        ArcheryButton = new javax.swing.JButton();
        GymnasticsButton = new javax.swing.JButton();
        TennisButton = new javax.swing.JButton();
        TableTennisButton = new javax.swing.JButton();
        VolleyballButton = new javax.swing.JButton();
        BasketballButton = new javax.swing.JButton();
        CricketButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SwimmingButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        SwimmingButton.setForeground(new java.awt.Color(222, 116, 9));
        SwimmingButton.setText("Swimming");
        SwimmingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwimmingButtonActionPerformed(evt);
            }
        });

        BadmintonButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BadmintonButton.setForeground(new java.awt.Color(0, 153, 51));
        BadmintonButton.setText("Badminton");
        BadmintonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadmintonButtonActionPerformed(evt);
            }
        });

        FootballButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        FootballButton.setForeground(new java.awt.Color(0, 153, 153));
        FootballButton.setText("Football");
        FootballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FootballButtonActionPerformed(evt);
            }
        });

        ArcheryButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ArcheryButton.setForeground(new java.awt.Color(0, 0, 204));
        ArcheryButton.setText("Archery");
        ArcheryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArcheryButtonActionPerformed(evt);
            }
        });

        GymnasticsButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        GymnasticsButton.setForeground(new java.awt.Color(102, 102, 0));
        GymnasticsButton.setText("Gymnastics");
        GymnasticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GymnasticsButtonActionPerformed(evt);
            }
        });

        TennisButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TennisButton.setForeground(new java.awt.Color(204, 0, 102));
        TennisButton.setText("Tennis");
        TennisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TennisButtonActionPerformed(evt);
            }
        });

        TableTennisButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TableTennisButton.setForeground(new java.awt.Color(0, 153, 102));
        TableTennisButton.setText("Table Tennis");
        TableTennisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableTennisButtonActionPerformed(evt);
            }
        });

        VolleyballButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        VolleyballButton.setForeground(new java.awt.Color(0, 153, 153));
        VolleyballButton.setText("Volleyball");
        VolleyballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolleyballButtonActionPerformed(evt);
            }
        });

        BasketballButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BasketballButton.setForeground(new java.awt.Color(153, 51, 255));
        BasketballButton.setText("Basketball");
        BasketballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketballButtonActionPerformed(evt);
            }
        });

        CricketButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        CricketButton.setForeground(new java.awt.Color(255, 102, 0));
        CricketButton.setText("Cricket");
        CricketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CricketButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Add Sports Schedule");

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 0, 0));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BadmintonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FootballButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ArcheryButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GymnasticsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SwimmingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TableTennisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TennisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CricketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BasketballButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VolleyballButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VolleyballButton)
                        .addGap(18, 18, 18)
                        .addComponent(BasketballButton)
                        .addGap(18, 18, 18)
                        .addComponent(CricketButton)
                        .addGap(18, 18, 18)
                        .addComponent(TennisButton)
                        .addGap(18, 18, 18)
                        .addComponent(TableTennisButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SwimmingButton)
                        .addGap(18, 18, 18)
                        .addComponent(BadmintonButton)
                        .addGap(18, 18, 18)
                        .addComponent(FootballButton)
                        .addGap(18, 18, 18)
                        .addComponent(ArcheryButton)
                        .addGap(18, 18, 18)
                        .addComponent(GymnasticsButton)))
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SwimmingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwimmingButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\SwimmingScheduleGUI.form");
    }//GEN-LAST:event_SwimmingButtonActionPerformed

    private void BadmintonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadmintonButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\BadmintonScheduleGUI.form");
    }//GEN-LAST:event_BadmintonButtonActionPerformed

    private void FootballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FootballButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\FootballScheduleGUI.form");
    }//GEN-LAST:event_FootballButtonActionPerformed

    private void ArcheryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArcheryButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\ArcheryScheduleGUI.form");
    }//GEN-LAST:event_ArcheryButtonActionPerformed

    private void GymnasticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GymnasticsButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\GymnasticsScheduleGUI.form");
    }//GEN-LAST:event_GymnasticsButtonActionPerformed

    private void TennisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TennisButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\TennisScheduleGUI.form");
    }//GEN-LAST:event_TennisButtonActionPerformed

    private void TableTennisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableTennisButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\TableTennisScheduleGUI.form");
    }//GEN-LAST:event_TableTennisButtonActionPerformed

    private void VolleyballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolleyballButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\VolleyballScheduleGUI.form");
    }//GEN-LAST:event_VolleyballButtonActionPerformed

    private void BasketballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketballButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\BasketballScheduleGUI.form");
    }//GEN-LAST:event_BasketballButtonActionPerformed

    private void CricketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CricketButtonActionPerformed
        AddSportSchedule.openFile("C:\\Program Files\\NetBeans 8.2\\bin\\netbeans.exe", "\\src\\rcsas\\CricketScheduleGUI.form");
    }//GEN-LAST:event_CricketButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        AddRecordGUI addRecordGUI = new AddRecordGUI();
        addRecordGUI.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecordSportScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecordSportScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecordSportScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecordSportScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecordSportScheduleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArcheryButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BadmintonButton;
    private javax.swing.JButton BasketballButton;
    private javax.swing.JButton CricketButton;
    private javax.swing.JButton FootballButton;
    private javax.swing.JButton GymnasticsButton;
    private javax.swing.JButton SwimmingButton;
    private javax.swing.JButton TableTennisButton;
    private javax.swing.JButton TennisButton;
    private javax.swing.JButton VolleyballButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
