/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author user
 */
public class AdminMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainGUI
     */
    public AdminMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddRecordButton = new javax.swing.JButton();
        DisplayRecordButton = new javax.swing.JButton();
        SearchRecordButton = new javax.swing.JButton();
        SortRecordButton = new javax.swing.JButton();
        ModifyRecordButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("ADMIN");

        AddRecordButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AddRecordButton.setForeground(new java.awt.Color(102, 102, 0));
        AddRecordButton.setText("Add Record");
        AddRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRecordButtonActionPerformed(evt);
            }
        });

        DisplayRecordButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DisplayRecordButton.setForeground(new java.awt.Color(51, 0, 255));
        DisplayRecordButton.setText("Display Record");
        DisplayRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRecordButtonActionPerformed(evt);
            }
        });

        SearchRecordButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SearchRecordButton.setForeground(new java.awt.Color(0, 204, 204));
        SearchRecordButton.setText("Search Record");
        SearchRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRecordButtonActionPerformed(evt);
            }
        });

        SortRecordButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SortRecordButton.setForeground(new java.awt.Color(51, 153, 0));
        SortRecordButton.setText("Sort Record");
        SortRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortRecordButtonActionPerformed(evt);
            }
        });

        ModifyRecordButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ModifyRecordButton.setForeground(new java.awt.Color(255, 51, 204));
        ModifyRecordButton.setText("Modify Record");
        ModifyRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyRecordButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 0, 51));
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SortRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayRecordButton)
                    .addComponent(ModifyRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddRecordButton)
                    .addComponent(DisplayRecordButton)
                    .addComponent(SearchRecordButton))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyRecordButton)
                    .addComponent(ExitButton)
                    .addComponent(SortRecordButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRecordButtonActionPerformed
        dispose();
        AddRecordGUI addRecordGUI = new AddRecordGUI();
        addRecordGUI.setVisible(true);
    }//GEN-LAST:event_AddRecordButtonActionPerformed

    private void DisplayRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRecordButtonActionPerformed
        dispose();
        DisplayRecordGUI displayRecordGUI = new DisplayRecordGUI();
        displayRecordGUI.setVisible(true);
    }//GEN-LAST:event_DisplayRecordButtonActionPerformed

    private void SearchRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRecordButtonActionPerformed
        dispose();
        SearchRecordGUI searchRecordGUI = new SearchRecordGUI();
        searchRecordGUI.setVisible(true);
    }//GEN-LAST:event_SearchRecordButtonActionPerformed

    private void SortRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortRecordButtonActionPerformed
        dispose();
        SortRecordGUI sortRecordGUI = new SortRecordGUI();
        sortRecordGUI.setVisible(true);
    }//GEN-LAST:event_SortRecordButtonActionPerformed

    private void ModifyRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyRecordButtonActionPerformed
        dispose();
        ModifyRecordGUI modifyRecordGUI = new ModifyRecordGUI();
        modifyRecordGUI.setVisible(true);
    }//GEN-LAST:event_ModifyRecordButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        dispose();
        RCSASMainGUI RCSASMainGUI = new RCSASMainGUI();
        RCSASMainGUI.setVisible(true);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRecordButton;
    private javax.swing.JButton DisplayRecordButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ModifyRecordButton;
    private javax.swing.JButton SearchRecordButton;
    private javax.swing.JButton SortRecordButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
