/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

import java.io.File;
import java.util.Scanner;

/**
 *
 * @author user
 */
public class DisplayRecordGUI extends javax.swing.JFrame {

    /**
     * Creates new form DisplayRecordGUI
     */
    public DisplayRecordGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CoachButton = new javax.swing.JButton();
        SportButton = new javax.swing.JButton();
        RegisteredStudentsButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayRecordOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Display Record");

        CoachButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CoachButton.setForeground(new java.awt.Color(204, 102, 255));
        CoachButton.setText("Coach");
        CoachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachButtonActionPerformed(evt);
            }
        });

        SportButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SportButton.setForeground(new java.awt.Color(255, 51, 153));
        SportButton.setText("Sport");
        SportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportButtonActionPerformed(evt);
            }
        });

        RegisteredStudentsButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        RegisteredStudentsButton.setForeground(new java.awt.Color(0, 102, 0));
        RegisteredStudentsButton.setText("Registered Students");
        RegisteredStudentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisteredStudentsButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BackButton.setForeground(new java.awt.Color(153, 0, 0));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        DisplayRecordOutput.setColumns(20);
        DisplayRecordOutput.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DisplayRecordOutput.setRows(5);
        DisplayRecordOutput.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DisplayRecordOutput.setEnabled(false);
        jScrollPane1.setViewportView(DisplayRecordOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(RegisteredStudentsButton)
                        .addComponent(SportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CoachButton, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(5, 5, 5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(BackButton)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(CoachButton)
                .addGap(18, 18, 18)
                .addComponent(SportButton)
                .addGap(18, 18, 18)
                .addComponent(RegisteredStudentsButton)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CoachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachButtonActionPerformed
        DisplayRecordOutput.setText("");
        displayRecord("coach_details.txt");
    }//GEN-LAST:event_CoachButtonActionPerformed

    private void SportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportButtonActionPerformed
        DisplayRecordOutput.setText("");
        displayRecord("sport_details.txt");
    }//GEN-LAST:event_SportButtonActionPerformed

    private void RegisteredStudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisteredStudentsButtonActionPerformed
        DisplayRecordOutput.setText("");
        displayRecord("student_details.txt");
    }//GEN-LAST:event_RegisteredStudentsButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        AdminMainGUI adminMainGUI = new AdminMainGUI();
        adminMainGUI.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void displayRecord(String fileName) {
        File f = new File(fileName);
        try {
            Scanner buffer = new Scanner(f);

            while (buffer.hasNext()) {
                String line = buffer.nextLine();
                DisplayRecordOutput.append(line + "\n");
            }
        } catch (Exception e) {
            System.out.println("File does not exist.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayRecordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CoachButton;
    private javax.swing.JTextArea DisplayRecordOutput;
    private javax.swing.JButton RegisteredStudentsButton;
    private javax.swing.JButton SportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
