/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;

/**
 *
 * @author user
 */
public class ModifyRecordSportGUI extends javax.swing.JFrame {

    /**
     * Creates new form ModifyRecordSportGUI
     */
    public ModifyRecordSportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CenterLocationInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CenterCodeInput = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        ChosenSportInput = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("SPORT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Sports Name: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Sport Center Location: ");

        CenterLocationInput.setEnabled(false);
        CenterLocationInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenterLocationInputActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Sport Center Code:");

        CenterCodeInput.setEnabled(false);

        SaveButton.setBackground(new java.awt.Color(204, 255, 204));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(0, 153, 102));
        SaveButton.setText("SAVE");
        SaveButton.setEnabled(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(204, 255, 204));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 0, 0));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ChosenSportInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Badminton", "Football", "Archery", "Gymnastics", "Volleyball", "Basketball", "Cricket", "Tennis", "Table Tennis" }));
        ChosenSportInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChosenSportInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(SaveButton))
                        .addGap(75, 75, 75)
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CenterLocationInput, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(CenterCodeInput))
                            .addComponent(ChosenSportInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ChosenSportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CenterLocationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CenterCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(BackButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CenterLocationInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenterLocationInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CenterLocationInputActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        String centerLocation = CenterLocationInput.getText();
        String centerCode = CenterCodeInput.getText();
        String chosenSport = (String)ChosenSportInput.getSelectedItem();
        
        saveRecord(chosenSport, centerLocation, centerCode);
        
        CenterLocationInput.setText("");
        CenterCodeInput.setText("");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        ModifyRecordGUI modfiyRecordGUI = new ModifyRecordGUI();
        modfiyRecordGUI.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ChosenSportInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChosenSportInputActionPerformed
        CenterLocationInput.setEnabled(true);
        CenterCodeInput.setEnabled(true);
        SaveButton.setEnabled(true);

        String chosenSport = (String)ChosenSportInput.getSelectedItem();
        searchSportDetails(chosenSport);
    }//GEN-LAST:event_ChosenSportInputActionPerformed

    private void searchSportDetails(String chosenSport) {
        File f = new File("sport_details.txt");
        try {
            Scanner buffer = new Scanner(f);
            
            while (buffer.hasNext()) {
                String line = buffer.nextLine();
                if (line.contains("SPORT NAME")) {
                    if (line.substring(12).equals(chosenSport)) {
                        oldCenterLocation = buffer.nextLine().substring(23);
                        oldCenterCode = buffer.nextLine().substring(19);
                        
                        CenterLocationInput.setText(oldCenterLocation);
                        CenterCodeInput.setText(oldCenterCode);
                        break;
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("File does not exist.");
        }
    }
    
    private String oldCenterLocation;
    private String oldCenterCode;
    
    private void saveRecord(String chosenSport, String centerLocation, String centerCode) {
        File f = new File("sport_details.txt");
        String content = "";
        String newContent = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader(f));
            String line = br.readLine();
            String oldCenterLocationLocal = this.oldCenterLocation;
            String oldCenterCodeLocal = this.oldCenterCode;
            
            while (line != null) {
                content += line + "\n";
                line = br.readLine();
            }
            br.close();
            
            Scanner s = new Scanner(content);
            
            while (s.hasNext()) {
                String line2 = s.nextLine();
                if (line2.contains("SPORT NAME")) {
                    if (line2.substring(12).equals(chosenSport)) {
                        newContent += line2 + "\n";
                        line2 = s.nextLine();
                        newContent += line2.substring(0, 23) + line2.substring(23).replaceAll(oldCenterLocationLocal, centerLocation) + "\n";
                        line2 = s.nextLine();
                        newContent += line2.substring(0, 19) + line2.substring(19).replaceAll(oldCenterCodeLocal, centerCode) + "\n";
                    } else {
                        newContent += line2 + "\n";
                    }
                } else {
                    newContent += line2 + "\n";
                }
            }
            
            FileWriter fw = new FileWriter(f);
            fw.write(newContent + "\n");
            fw.close();
        } catch (Exception e) {
            System.out.println("File does not exist.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordSportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordSportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordSportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordSportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyRecordSportGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField CenterCodeInput;
    private javax.swing.JTextField CenterLocationInput;
    private javax.swing.JComboBox<String> ChosenSportInput;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
