/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/**
 *
 * @author sazza
 */
public class ModifyRecordCoachGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddCoachGUI
     */
    public ModifyRecordCoachGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContactNumberInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddressInput = new javax.swing.JTextField();
        NameInput = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ChosenSportInput = new javax.swing.JComboBox<>();
        DateJoinInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DateTerminatedInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        HourlyPayRateInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContactNumberInput.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Date Joined:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Modify Coach Record");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Date Terminated:");

        BackButton.setBackground(new java.awt.Color(204, 255, 204));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 0, 51));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Contact Number:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Name:");

        AddressInput.setEnabled(false);

        NameInput.setEnabled(false);
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(204, 204, 255));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(0, 153, 0));
        SaveButton.setText("SAVE");
        SaveButton.setEnabled(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Address:");

        ChosenSportInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Badminton", "Football", "Archery", "Gymnastics", "Volleyball", "Basketball", "Cricket", "Tennis", "Table Tennis" }));
        ChosenSportInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChosenSportInputActionPerformed(evt);
            }
        });

        DateJoinInput.setEnabled(false);
        DateJoinInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateJoinInputActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Sport Name:");

        DateTerminatedInput.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Hourly Pay Rate:");

        HourlyPayRateInput.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateJoinInput, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTerminatedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChosenSportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HourlyPayRateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChosenSportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateJoinInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateTerminatedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HourlyPayRateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(BackButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        ModifyRecordGUI modfiyRecordGUI = new ModifyRecordGUI();
        modfiyRecordGUI.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        String name = NameInput.getText();
        String dateJoined = DateJoinInput.getText();
        String dateTerminated = DateTerminatedInput.getText();
        String contactNumber = ContactNumberInput.getText();
        String address = AddressInput.getText();
        String hourlyPayRate = HourlyPayRateInput.getText();
        
        saveRecord(name, dateJoined, dateTerminated, contactNumber, address, hourlyPayRate);
        
        NameInput.setText("");
        DateJoinInput.setText("");
        DateTerminatedInput.setText("");
        ContactNumberInput.setText("");
        AddressInput.setText("");
        HourlyPayRateInput.setText("");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void ChosenSportInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChosenSportInputActionPerformed
        NameInput.setEnabled(true);
        DateJoinInput.setEnabled(true);
        DateTerminatedInput.setEnabled(true);
        ContactNumberInput.setEnabled(true);
        AddressInput.setEnabled(true);
        HourlyPayRateInput.setEnabled(true);
        SaveButton.setEnabled(true);
        
        String chosenSport = (String)ChosenSportInput.getSelectedItem();
        searchCoachDetails(chosenSport);
    }//GEN-LAST:event_ChosenSportInputActionPerformed

    private void DateJoinInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateJoinInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateJoinInputActionPerformed

    private void searchCoachDetails(String chosenSport) {
        File f = new File("coach_details.txt");
        try {
            Scanner buffer = new Scanner(f);
            List<String> temp = new ArrayList<>();
            
            while (buffer.hasNext()) {
                String line = buffer.nextLine();
                temp.add(line);
                if (line.contains("SPORT")) {
                    if (line.substring(7).equals(chosenSport)) {
                        oldName = temp.get(temp.size() - 8).substring(6);
                        oldDateJoined = temp.get(temp.size() - 7).substring(13);
                        oldDateTerminated = temp.get(temp.size() - 6).substring(17);
                        oldContactNumber = temp.get(temp.size() - 5).substring(7);
                        oldAddress = temp.get(temp.size() - 4).substring(9);
                        oldHourlyPayRate = buffer.nextLine().substring(10);
                        
                        NameInput.setText(oldName);
                        DateJoinInput.setText(oldDateJoined);
                        DateTerminatedInput.setText(oldDateTerminated);
                        ContactNumberInput.setText(oldContactNumber);
                        AddressInput.setText(oldAddress);
                        HourlyPayRateInput.setText(oldHourlyPayRate);
                        break;
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("File does not exist.");
        }
    }
    
    private String oldName;
    private String oldDateJoined;
    private String oldDateTerminated;
    private String oldContactNumber;
    private String oldAddress;
    private String oldHourlyPayRate;
    
    private void saveRecord(String name, String dateJoined, String dateTerminated, String contactNumber, String address, String hourlyPayRate) {
        File f = new File("coach_details.txt");
        String content = "";
        String newContent = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader(f));
            String line = br.readLine();
            String oldNameLocal = this.oldName;
            String oldDateJoinedLocal = this.oldDateJoined;
            String oldDateTerminatedLocal = this.oldDateTerminated;
            String oldContactNumberLocal = this.oldContactNumber;
            String oldAddressLocal = this.oldAddress;
            String oldHourlyPayRateLocal = this.oldHourlyPayRate;
            
            while (line != null) {
                content += line + "\n";
                line = br.readLine();
            }
            br.close();
            
            Scanner s = new Scanner(content);
            
            while (s.hasNext()) {
                String line2 = s.nextLine();
                if (line2.contains("NAME")) {
                    if (line2.substring(6).equals(oldNameLocal)) {
                        newContent += line2.substring(0, 6) + line2.substring(6).replaceAll(oldNameLocal, name) + "\n";
                        line2 = s.nextLine();
                        newContent += line2.substring(0, 13) + line2.substring(13).replaceAll(oldDateJoinedLocal, dateJoined) + "\n";
                        line2 = s.nextLine();
                        newContent += line2.substring(0, 17) + line2.substring(17).replaceAll(oldDateTerminatedLocal, dateTerminated) + "\n";
                        line2 = s.nextLine();
                        newContent += line2.substring(0, 7) + line2.substring(7).replaceAll(oldContactNumberLocal, contactNumber) + "\n";
                        line2 = s.nextLine();
                        newContent += line2.substring(0, 9) + line2.substring(9).replaceAll(oldAddressLocal, address) + "\n";
                        for (int i = 0; i <= 2; i++) {
                            line2 = s.nextLine();
                            newContent += line2 + "\n";
                        }
                        line2 = s.nextLine();
                        newContent += line2.substring(0, 10) + line2.substring(10).replaceAll(oldHourlyPayRateLocal, hourlyPayRate) + "\n";
                        line2 = s.nextLine();
                        newContent += line2 + "\n";
                    } else {
                        newContent += line2 + "\n";
                    }
                } else {
                    newContent += line2 + "\n";
                }
            }
            
            FileWriter fw = new FileWriter(f);
            fw.write(newContent + "\n");
            fw.close();
        } catch (Exception e) {
            System.out.println("File does not exist.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordCoachGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordCoachGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordCoachGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordCoachGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyRecordCoachGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressInput;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> ChosenSportInput;
    private javax.swing.JTextField ContactNumberInput;
    private javax.swing.JTextField DateJoinInput;
    private javax.swing.JTextField DateTerminatedInput;
    private javax.swing.JTextField HourlyPayRateInput;
    private javax.swing.JTextField NameInput;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
