/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author user
 */
public class ModifyRecordGUI extends javax.swing.JFrame {

    /**
     * Creates new form ModifyRecordGUI
     */
    public ModifyRecordGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CoachButton = new javax.swing.JButton();
        SportButton = new javax.swing.JButton();
        SportsScheduleButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("MODIFY RECORD");

        CoachButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CoachButton.setForeground(new java.awt.Color(222, 105, 33));
        CoachButton.setText("Coach");
        CoachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachButtonActionPerformed(evt);
            }
        });

        SportButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SportButton.setForeground(new java.awt.Color(204, 10, 124));
        SportButton.setText("Sport");
        SportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportButtonActionPerformed(evt);
            }
        });

        SportsScheduleButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SportsScheduleButton.setForeground(new java.awt.Color(0, 153, 0));
        SportsScheduleButton.setText("Sports Schedule");
        SportsScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportsScheduleButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BackButton.setForeground(new java.awt.Color(153, 0, 0));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CoachButton)
                            .addComponent(SportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(SportsScheduleButton)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(CoachButton)
                .addGap(37, 37, 37)
                .addComponent(SportButton)
                .addGap(30, 30, 30)
                .addComponent(SportsScheduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CoachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachButtonActionPerformed
        dispose();
        ModifyRecordCoachGUI modifyRecordCoachGUI = new ModifyRecordCoachGUI();
        modifyRecordCoachGUI.setVisible(true);
    }//GEN-LAST:event_CoachButtonActionPerformed

    private void SportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportButtonActionPerformed
        dispose();
        ModifyRecordSportGUI modifyRecordSportGUI = new ModifyRecordSportGUI();
        modifyRecordSportGUI.setVisible(true);
    }//GEN-LAST:event_SportButtonActionPerformed

    private void SportsScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportsScheduleButtonActionPerformed
        dispose();
        ModifyRecordSportScheduleGUI modifyRecordSportScheduleGUI = new ModifyRecordSportScheduleGUI();
        modifyRecordSportScheduleGUI.setVisible(true);
    }//GEN-LAST:event_SportsScheduleButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        AdminMainGUI adminMainGUI = new AdminMainGUI();
        adminMainGUI.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyRecordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CoachButton;
    private javax.swing.JButton SportButton;
    private javax.swing.JButton SportsScheduleButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
