/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author sazza
 */
public class RegisterStudentViewDetailsGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudentViewDetailsGUI
     */
    public RegisterStudentViewDetailsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CoachButton = new javax.swing.JButton();
        SelfRecordButton = new javax.swing.JButton();
        SportScheduleButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setText("ACCESS DETAILS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CoachButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CoachButton.setForeground(new java.awt.Color(0, 153, 51));
        CoachButton.setText("COACH");
        CoachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachButtonActionPerformed(evt);
            }
        });

        SelfRecordButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SelfRecordButton.setForeground(new java.awt.Color(51, 51, 255));
        SelfRecordButton.setText("SELF-RECORD");
        SelfRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelfRecordButtonActionPerformed(evt);
            }
        });

        SportScheduleButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SportScheduleButton.setForeground(new java.awt.Color(255, 153, 0));
        SportScheduleButton.setText("SPORT SCHEDULE");
        SportScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportScheduleButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(204, 255, 204));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 0, 0));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 204));
        jLabel2.setText("ACCESS DETAILS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SportScheduleButton)
                            .addComponent(SelfRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CoachButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(BackButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(CoachButton)
                .addGap(33, 33, 33)
                .addComponent(SelfRecordButton)
                .addGap(36, 36, 36)
                .addComponent(SportScheduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CoachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachButtonActionPerformed
        dispose();
        RegisterStudentViewCoachGUI registerStudentViewCoachGUI = new RegisterStudentViewCoachGUI();
        registerStudentViewCoachGUI.setVisible(true);
    }//GEN-LAST:event_CoachButtonActionPerformed

    private void SelfRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelfRecordButtonActionPerformed
        dispose();
        RegisterStudentViewSelfRecordGUI registerStudentViewSelfRecordGUI = new RegisterStudentViewSelfRecordGUI();
        registerStudentViewSelfRecordGUI.setVisible(true);
    }//GEN-LAST:event_SelfRecordButtonActionPerformed

    private void SportScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportScheduleButtonActionPerformed
        dispose();
        RegisterStudentViewSportScheduleGUI registerStudentViewSportScheduleGUI = new RegisterStudentViewSportScheduleGUI();
        registerStudentViewSportScheduleGUI.setVisible(true);
    }//GEN-LAST:event_SportScheduleButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        StudentMainGUI studentMainGUI = new StudentMainGUI();
        studentMainGUI.setVisible(true);
                
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudentViewDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudentViewDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudentViewDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudentViewDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudentViewDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CoachButton;
    private javax.swing.JButton SelfRecordButton;
    private javax.swing.JButton SportScheduleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
