/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author user
 */
public class ViewDetailsGUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewDetailsGUI
     */
    public ViewDetailsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SwimmingButton = new javax.swing.JButton();
        BadmintonButton = new javax.swing.JButton();
        FootballButton = new javax.swing.JButton();
        ArcheryButton = new javax.swing.JButton();
        GymnasticsButton = new javax.swing.JButton();
        TennisButton = new javax.swing.JButton();
        TableTennisButton = new javax.swing.JButton();
        VolleyballButton = new javax.swing.JButton();
        BasketballButton = new javax.swing.JButton();
        CricketButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Sports");

        SwimmingButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        SwimmingButton.setForeground(new java.awt.Color(0, 204, 204));
        SwimmingButton.setText("Swimming");
        SwimmingButton.setBorderPainted(false);
        SwimmingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwimmingButtonActionPerformed(evt);
            }
        });

        BadmintonButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BadmintonButton.setForeground(new java.awt.Color(102, 153, 0));
        BadmintonButton.setText("Badminton");
        BadmintonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadmintonButtonActionPerformed(evt);
            }
        });

        FootballButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        FootballButton.setForeground(new java.awt.Color(255, 51, 255));
        FootballButton.setText("Football");
        FootballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FootballButtonActionPerformed(evt);
            }
        });

        ArcheryButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ArcheryButton.setForeground(new java.awt.Color(0, 204, 51));
        ArcheryButton.setText("Archery");
        ArcheryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArcheryButtonActionPerformed(evt);
            }
        });

        GymnasticsButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        GymnasticsButton.setForeground(new java.awt.Color(153, 153, 255));
        GymnasticsButton.setText("Gymnastics");
        GymnasticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GymnasticsButtonActionPerformed(evt);
            }
        });

        TennisButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TennisButton.setForeground(new java.awt.Color(204, 0, 102));
        TennisButton.setText("Tennis");
        TennisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TennisButtonActionPerformed(evt);
            }
        });

        TableTennisButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TableTennisButton.setForeground(new java.awt.Color(18, 178, 245));
        TableTennisButton.setText("Table Tennis");
        TableTennisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableTennisButtonActionPerformed(evt);
            }
        });

        VolleyballButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        VolleyballButton.setForeground(new java.awt.Color(0, 51, 255));
        VolleyballButton.setText("Volleyball");
        VolleyballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolleyballButtonActionPerformed(evt);
            }
        });

        BasketballButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BasketballButton.setForeground(new java.awt.Color(153, 0, 153));
        BasketballButton.setText("Basketball");
        BasketballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketballButtonActionPerformed(evt);
            }
        });

        CricketButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        CricketButton.setForeground(new java.awt.Color(0, 102, 102));
        CricketButton.setText("Cricket");
        CricketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CricketButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(204, 255, 204));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        BackButton.setForeground(new java.awt.Color(221, 22, 46));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BadmintonButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(FootballButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ArcheryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SwimmingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GymnasticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TableTennisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TennisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CricketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BasketballButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VolleyballButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(BackButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VolleyballButton)
                        .addGap(18, 18, 18)
                        .addComponent(BasketballButton)
                        .addGap(18, 18, 18)
                        .addComponent(CricketButton)
                        .addGap(18, 18, 18)
                        .addComponent(TennisButton)
                        .addGap(18, 18, 18)
                        .addComponent(TableTennisButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SwimmingButton)
                        .addGap(18, 18, 18)
                        .addComponent(BadmintonButton)
                        .addGap(18, 18, 18)
                        .addComponent(FootballButton)
                        .addGap(18, 18, 18)
                        .addComponent(ArcheryButton)
                        .addGap(18, 18, 18)
                        .addComponent(GymnasticsButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackButton))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FootballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FootballButtonActionPerformed
        dispose();    
        FootballScheduleGUI footballScheduleGUI = new FootballScheduleGUI();
        footballScheduleGUI.setVisible(true);
    }//GEN-LAST:event_FootballButtonActionPerformed

    private void SwimmingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwimmingButtonActionPerformed
        dispose();    
        SwimmingScheduleGUI swimmingScheduleGUI = new SwimmingScheduleGUI();
        swimmingScheduleGUI.setVisible(true);
    }//GEN-LAST:event_SwimmingButtonActionPerformed

    private void TableTennisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableTennisButtonActionPerformed
        dispose();    
        TableTennisScheduleGUI tableTennisScheduleGUI = new TableTennisScheduleGUI();
        tableTennisScheduleGUI.setVisible(true);
    }//GEN-LAST:event_TableTennisButtonActionPerformed

    private void BadmintonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadmintonButtonActionPerformed
        dispose();    
        BadmintonScheduleGUI badmintonScheduleGUI = new BadmintonScheduleGUI();
        badmintonScheduleGUI.setVisible(true);
    }//GEN-LAST:event_BadmintonButtonActionPerformed

    private void ArcheryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArcheryButtonActionPerformed
        dispose();    
        ArcheryScheduleGUI archeryScheduleGUI = new ArcheryScheduleGUI();
        archeryScheduleGUI.setVisible(true);
    }//GEN-LAST:event_ArcheryButtonActionPerformed

    private void GymnasticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GymnasticsButtonActionPerformed
        dispose();    
        GymnasticsScheduleGUI gymnasticsScheduleGUI = new GymnasticsScheduleGUI();
        gymnasticsScheduleGUI.setVisible(true);
    }//GEN-LAST:event_GymnasticsButtonActionPerformed

    private void VolleyballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolleyballButtonActionPerformed
        dispose();    
        VolleyballScheduleGUI volleyballScheduleGUI = new VolleyballScheduleGUI();
        volleyballScheduleGUI.setVisible(true);
    }//GEN-LAST:event_VolleyballButtonActionPerformed

    private void BasketballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketballButtonActionPerformed
        dispose();    
        BasketballScheduleGUI basketballScheduleGUI = new BasketballScheduleGUI();
        basketballScheduleGUI.setVisible(true);
    }//GEN-LAST:event_BasketballButtonActionPerformed

    private void CricketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CricketButtonActionPerformed
        dispose();    
        CricketScheduleGUI cricketScheduleGUI = new CricketScheduleGUI();
        cricketScheduleGUI.setVisible(true);
    }//GEN-LAST:event_CricketButtonActionPerformed

    private void TennisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TennisButtonActionPerformed
        dispose();    
        TennisScheduleGUI tennisScheduleGUI = new TennisScheduleGUI();
        tennisScheduleGUI.setVisible(true);
    }//GEN-LAST:event_TennisButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        RCSASMainGUI RCSASMainGUI = new RCSASMainGUI();
        RCSASMainGUI.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        StudentRegisterGUI studentRegisterGUI = new StudentRegisterGUI();
        studentRegisterGUI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArcheryButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BadmintonButton;
    private javax.swing.JButton BasketballButton;
    private javax.swing.JButton CricketButton;
    private javax.swing.JButton FootballButton;
    private javax.swing.JButton GymnasticsButton;
    private javax.swing.JButton SwimmingButton;
    private javax.swing.JButton TableTennisButton;
    private javax.swing.JButton TennisButton;
    private javax.swing.JButton VolleyballButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
